import { describe, it, expect } from 'vitest';
import { calculateFreshBatch, calculateRegrind, generateVarianceTable } from '../calcEngine';
import { defaultIngredients } from '../defaultFormulation';
import type { IngredientLine } from '../types';

// Golden values generated by running the prototype's exact original calc()
// logic (unmodified) against its own hardcoded presets. See golden-gen.js
// and golden-values.json at the repo root — this is the byte-parity proof.

function ingredientsWithActivePercent(percent: number): IngredientLine[] {
  return defaultIngredients().map((i) => (i.role === 'active' ? { ...i, percentOfBlend: percent } : i));
}

describe('calculateFreshBatch — preset1_fresh', () => {
  const result = calculateFreshBatch({
    tabletCount: 133623,
    targetWeightG: 0.69,
    targetActiveMgPerTablet: 35,
    ingredients: ingredientsWithActivePercent(55.5),
  });

  it('matches golden totalBlendG', () => {
    expect(result!.totalBlendG).toBeCloseTo(92199.87, 6);
  });

  it('matches golden active grams', () => {
    expect(result!.ingredientGrams['active']).toBeCloseTo(51170.92785, 5);
  });

  it('matches golden emdex (filler) grams', () => {
    expect(result!.ingredientGrams['emdex']).toBeCloseTo(34574.95124999999, 5);
  });

  it('matches golden pvpp grams', () => {
    expect(result!.ingredientGrams['pvpp']).toBeCloseTo(4609.9935, 5);
  });

  it('matches golden magstearate grams', () => {
    expect(result!.ingredientGrams['magstearate']).toBeCloseTo(1843.9974, 5);
  });

  it('matches golden emdex percent (37.5%)', () => {
    expect(result!.ingredientPercents['emdex']).toBeCloseTo(37.49999999999999, 6);
  });
});

describe('calculateRegrind (bulkPercent) — preset2_regrindOptA', () => {
  const result = calculateRegrind({
    potency: { method: 'bulkPercent', percent: 55.5 },
    regroundPowderG: 8000,
    targetActiveMgPerTablet: 60,
    targetWeightG: 1.15,
    fillerIngredientName: 'Emdex',
    alreadyPresentIngredientNames: ['Magnesium stearate', 'PVPP XL'],
  });

  it('matches golden tabletCount (74000)', () => {
    expect(result!.tabletCount).toBe(74000);
  });

  it('matches golden totalBlendG (85100)', () => {
    expect(result!.totalBlendG).toBeCloseTo(85100, 6);
  });

  it('matches golden fillerAddG (77100)', () => {
    expect(result!.fillerAddG).toBeCloseTo(77100, 6);
  });

  it('matches golden activeInOldPowderG (4440)', () => {
    expect(result!.activeInOldPowderG).toBeCloseTo(4440, 6);
  });

  it('matches golden actualMgPerTablet (60)', () => {
    expect(result!.actualMgPerTablet).toBeCloseTo(60, 6);
  });

  it('matches golden freshActiveG (0 — old powder covers full batch)', () => {
    expect(result!.freshActiveG).toBe(0);
  });
});

describe('calculateRegrind (mgPerTablet) — preset0_regrindOptB', () => {
  const result = calculateRegrind({
    potency: { method: 'mgPerTablet', mgPerOldTablet: 20.1, oldTabletWeightG: 0.27 },
    regroundPowderG: 14500,
    targetActiveMgPerTablet: 35,
    targetWeightG: 0.8,
    fillerIngredientName: 'Emdex',
    alreadyPresentIngredientNames: ['Magnesium stearate', 'PVPP XL'],
  });

  it('matches golden effectivePotency', () => {
    expect(result!.effectivePotency).toBeCloseTo(0.07444444444444445, 10);
  });

  it('matches golden tabletCount (30841)', () => {
    expect(result!.tabletCount).toBe(30841);
  });

  it('matches golden totalBlendG', () => {
    expect(result!.totalBlendG).toBeCloseTo(24672.926865671645, 6);
  });

  it('matches golden fillerAddG', () => {
    expect(result!.fillerAddG).toBeCloseTo(10172.926865671645, 6);
  });

  it('matches golden activeInOldPowderG', () => {
    expect(result!.activeInOldPowderG).toBeCloseTo(1079.4444444444446, 6);
  });

  it('matches golden actualMgPerTablet', () => {
    expect(result!.actualMgPerTablet).toBeCloseTo(35.00030623016259, 6);
  });
});

describe('generateVarianceTable', () => {
  it('matches golden 7-row table for the fresh preset (target 0.69g / 35mg)', () => {
    const rows = generateVarianceTable(0.69, 35);
    expect(rows).toEqual([
      { weightG: 0.675, step: -3, potencyMg: 34.239 },
      { weightG: 0.68, step: -2, potencyMg: 34.493 },
      { weightG: 0.685, step: -1, potencyMg: 34.746 },
      { weightG: 0.69, step: 0, potencyMg: 35 },
      { weightG: 0.695, step: 1, potencyMg: 35.254 },
      { weightG: 0.7, step: 2, potencyMg: 35.507 },
      { weightG: 0.705, step: 3, potencyMg: 35.761 },
    ]);
  });

  it('matches golden 7-row table for the regrind option-A preset (target 1.15g / 60mg)', () => {
    const rows = generateVarianceTable(1.15, 60);
    expect(rows).toEqual([
      { weightG: 1.135, step: -3, potencyMg: 59.217 },
      { weightG: 1.14, step: -2, potencyMg: 59.478 },
      { weightG: 1.145, step: -1, potencyMg: 59.739 },
      { weightG: 1.15, step: 0, potencyMg: 60 },
      { weightG: 1.155, step: 1, potencyMg: 60.261 },
      { weightG: 1.16, step: 2, potencyMg: 60.522 },
      { weightG: 1.165, step: 3, potencyMg: 60.783 },
    ]);
  });
});

describe('validation guards', () => {
  it('throws if no active ingredient', () => {
    const bad = defaultIngredients().map((i) => (i.role === 'active' ? { ...i, role: 'other' as const } : i));
    expect(() =>
      calculateFreshBatch({
        tabletCount: 100,
        targetWeightG: 0.5,
        targetActiveMgPerTablet: 10,
        ingredients: bad,
      })
    ).toThrow(/exactly one ingredient with role 'active'/);
  });

  it('throws if two ingredients are calculatedByDifference', () => {
    const bad = ingredientsWithActivePercent(50).map((i) =>
      i.id === 'pvpp' ? { ...i, calculatedByDifference: true } : i
    );
    expect(() =>
      calculateFreshBatch({
        tabletCount: 100,
        targetWeightG: 0.5,
        targetActiveMgPerTablet: 10,
        ingredients: bad,
      })
    ).toThrow(/exactly one ingredient with calculatedByDifference/);
  });

  it('returns null (not throw) for incomplete but validly-shaped input', () => {
    const result = calculateFreshBatch({
      tabletCount: 0,
      targetWeightG: 0.5,
      targetActiveMgPerTablet: 10,
      ingredients: ingredientsWithActivePercent(50),
    });
    expect(result).toBeNull();
  });
});
